// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/BevisDev/BevisBot/internal"
	"github.com/BevisDev/BevisBot/internal/config"
	"github.com/BevisDev/BevisBot/internal/controller"
	"github.com/BevisDev/BevisBot/internal/repository"
	"github.com/BevisDev/BevisBot/internal/router"
	"github.com/BevisDev/BevisBot/internal/service"
)

// Injectors from app.go:

func InitializeApp() (*internal.App, error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, err
	}
	openAI := config.OpenAIProvider(configConfig)
	openAIService, err := service.NewOpenAIService(openAI)
	if err != nil {
		return nil, err
	}
	botService := service.NewBotService(openAIService)
	webhookController := controller.NewWebhookController(botService)
	taskRepository := repository.NewTaskRepository()
	taskService := service.NewTaskService(taskRepository)
	taskController := controller.NewTaskController(taskService)
	routerRouter := router.New(webhookController, taskController)
	app, err := internal.New(configConfig, routerRouter, botService)
	if err != nil {
		return nil, err
	}
	return app, nil
}
