// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/BevisDev/BevisBot/internal/app/service/notification"
	"github.com/BevisDev/BevisBot/internal/di/provider"
)

// Injectors from notification_di.go:

func NewNotificationServiceDI() notification.INotification {
	iNotification := notification.NewNotification()
	return iNotification
}

// Injectors from service_di.go:

func NewServiceDI() *provider.ServiceProvider {
	iNotification := NewNotificationServiceDI()
	serviceProvider := provider.NewServiceProvider(iNotification)
	return serviceProvider
}
