server:
  name: BevisBot
  port: 8080
  profile: dev
  version: 0.0.1

# Logger
logger:
  dirName: ./logs
  fileName: app.log

# Database
database:
  host:
  port: 5432
  username: postgres
  password: postgres
  db: bevis
  maxOpenConns: 25
  maxIdleConns: 10

# TgBot
tgBot:
  chatID:
  token:

# OpenAI
openai:
  apiKey: 
