server:
  name: BevisBot
  port: 8080
  profile: prod
  version: 0.0.1

# Logger
logger:
  dirName: ./logs
  fileName: app.log

# Database
database:
  host:
  port:
  username:
  password:
  db: 
  maxOpenConns: 25
  maxIdleConns: 10

# TgBot
tgBot:
  chatID:
  token:

# OpenAI
openai:
  apiKey: