# SERVER
server:
  name: BevisBot
  profile: uat
  trustedProxies:
    - 127.0.0.1
  port: 8080
  masterKey:
  version: 1.0.0

# LOGGER
logger:
  isRotate: false
  dirName: ./logs
  fileName: app.log
  maxSize: 5
  maxBackup: 30
  maxAge: 30
  compress: true