name: CI application
on:
  push:
    branches: [master]

jobs:
  build:
    uses: BevisOrg/cicd/.github/workflows/test.yml@master
  deploy:
    uses: BevisOrg/cicd/.github/workflows/test.yml@master
  
